name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: dev-cd
    
    permissions:
      id-token: write
 
    steps:
      #
      # Checkout the source code.
      #
      - name: Checkout the source code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0

      #
      # Login to Azure.
      #
      - name: Login to Azure
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      #
      # Upload files.
      #
      - name: Upload files
        uses: azure/CLI@fa0f960f00db49b95fdb54328a767aee31e80105
        with:
          inlineScript: |
            az storage blob upload-batch --destination acquirers --account-name milconf --destination-path / --source src/main/conf/acquirers
            az storage blob upload-batch --destination clients   --account-name milconf --destination-path / --source src/main/conf/clients
            az storage blob upload-batch --destination roles     --account-name milconf --destination-path / --source src/main/conf/roles
            az storage blob upload-batch --destination users     --account-name milconf --destination-path / --source src/main/conf/users